# https://nikitabobko.github.io/AeroSpace/guide#config-samples

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
# Possible values: tiles|accordion
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


after-startup-command = ['exec-and-forget sketchybar']


# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]


[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 30
outer.right = 0


[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-esc = 'layout floating tiling'
# alt-s = 'layout v_accordion'
# alt-tab = 'workspace-back-and-forth'


alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-shift-d = 'move-mouse monitor-force-center'


alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'


alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'


alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'


# alt-a = 'workspace 1' # Alacritty
# alt-b = 'workspace b' # browser
# alt-c = 'workspace c' # VS Code
# alt-l = 'workspace 2' # Alacritty
# alt-s = 'workspace S' # Spotify
# alt-g = 'workspace G' # Messages
# alt-f = 'workspace f' # Figma
# alt-d = 'workspace D' # Dorion
# alt-o = 'workspace o' # Obsidian
# alt-t = 'workspace t' # Terminal
# alt-n = 'workspace n' # Notion
# alt-shift-f = 'workspace F' # Finder 
# alt-shift-k = 'workspace K' # Keepassxc
# alt-v = 'workspace V' # Davinci 

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-m = 'move-workspace-to-monitor --wrap-around next'


# Find app-id `mdls -name kMDItemCFBundleIdentifier /Applications/AppName.app`

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'move-node-to-workspace 1' 

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace 1' 


[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace 2' 

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
run = 'move-node-to-workspace 4' 


[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'ai.perplexity.comet'
run = 'move-node-to-workspace 5' 

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = 'move-node-to-workspace 6'



#-----------Free Flow---------------------
[[on-window-detected]]
if.app-id = 'com.apple.clock'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.eltima.elmedia6.mas'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.tdesktop.Telegram'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'layout floating'